version: 2.1

executors:
  unity:
    docker:
      - image: gableroux/unity3d:2017.4.27f1

jobs:
  create-package:
    executor: unity
    steps:
      - checkout
      - run: mkdir -p /root/.cache/unity3d
      - run: mkdir -p /root/.local/share/unity3d/Unity
      - run: echo $UNITY_LICENSE | base64 --decode > /root/.local/share/unity3d/Unity/Unity_lic.ulf
      - run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -projectPath /root/project -executeMethod PackageExport.Export
      - store_artifacts:
          path: ./Packages

workflows:
  version: 2
  build:
    jobs:
      - create-package
