version: 2.1

executors:
  unity:
    docker:
      - image: gableroux/unity3d:2017.4.27f1

jobs:
  create-package:
    executor: unity
    steps:
      - checkout
      - run: echo $UNITY_LICENSE | base64 --decode > .circleci/Unity.ulf
      - run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -manualLicenseFile .circleci/Unity.ulf || exit 0
      - run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -projectPath . -executeMethod PackageExport.Export
      - store_artifacts:
          path: ./Packages

workflows:
  version: 2
  build:
    jobs:
      - create-package
